import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Términos y Condiciones de Uso — Starkio Labs",
  description: "Términos y condiciones de uso del sitio web de Starkio Labs SpA.",
};

const contents = [
  ["titular", "Identificación del titular"], ["s1", "1. Objeto y aceptación"],
  ["s2", "2. Descripción del Sitio y los servicios"], ["s3", "3. Condiciones de acceso y uso"],
  ["s4", "4. Propiedad intelectual e industrial"], ["s5", "5. Responsabilidad y garantías"],
  ["s6", "6. Enlaces a sitios de terceros"], ["s7", "7. Empresas del holding"],
  ["s8", "8. Política de uso aceptable"], ["s9", "9. Confidencialidad"],
  ["s10", "10. Protección de datos personales"], ["s11", "11. Comunicaciones electrónicas"],
  ["s12", "12. Nulidad parcial"], ["s13", "13. Renuncia"], ["s14", "14. Cesión"],
  ["s15", "15. Legislación aplicable y jurisdicción"], ["s16", "16. Controversias y mediación"],
  ["s17", "17. Vigencia y modificaciones"], ["s18", "18. Contacto"],
] as const;

const owner = [
  ["Empresa", "Starkio Labs SpA"], ["RUT", "[COMPLETAR ANTES DE PUBLICAR]"],
  ["Domicilio", "Santiago, Región Metropolitana, Chile"], ["Correo", "contacto@starkio.io"],
  ["Sitio web", "https://starkio.io"], ["Representante legal", "Ernesto Arturo Starck Hernández"],
];

function DetailTable({ data }: { data: string[][] }) {
  return <div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full text-left text-xs"><tbody>{data.map(([label, value]) => <tr key={label} className="border-b border-white/5 last:border-0"><td className="whitespace-nowrap px-4 py-3 font-medium text-starkio-cloud/40">{label}</td><td className="px-4 py-3 text-starkio-cloud/70">{value}</td></tr>)}</tbody></table></div>;
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id}><h2 className="mb-3 text-lg font-semibold text-starkio-cloud">{title}</h2>{children}</section>;
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-void px-6 py-24">
      <div className="mx-auto max-w-3xl text-sm leading-relaxed text-starkio-cloud/70">
        <Link href="/" className="text-sm text-starkio-purple hover:underline">← Volver al inicio</Link>
        <p className="mt-8 mb-3 font-mono text-xs tracking-widest text-starkio-purple">STARKIO LABS SPA</p>
        <h1 className="mb-3 text-display-md font-bold text-starkio-cloud">Términos y Condiciones de Uso</h1>
        <p className="mb-12 text-starkio-cloud/40">Versión 1.0 · Vigente desde 16 de septiembre de 2026</p>

        <nav aria-label="Contenidos de los términos" className="mb-14 rounded-xl border border-white/10 p-6"><p className="mb-4 text-xs tracking-widest text-starkio-cloud/40">CONTENIDOS</p><ol className="grid list-decimal list-inside gap-x-8 gap-y-2 sm:grid-cols-2">{contents.map(([id, label]) => <li key={id} className="marker:text-starkio-cloud/30"><a href={`#${id}`} className="hover:text-starkio-cloud transition-colors">{label.replace(/^\d+\.\s/, "")}</a></li>)}</ol></nav>

        <div className="space-y-14">
          <Section id="titular" title="Identificación del Titular del Sitio"><DetailTable data={owner} /><p className="mt-3 text-xs text-red-400">El RUT queda pendiente de completar antes de publicar este sitio.</p></Section>

          <Section id="s1" title="1. Objeto y aceptación"><p className="mb-3">Estos Términos y Condiciones de Uso regulan el acceso, navegación y uso de https://starkio.io, así como los servicios, contenidos y funcionalidades ofrecidos por Starkio Labs SpA (&quot;Starkio&quot; o &quot;la Empresa&quot;).</p><p className="mb-3">El acceso al Sitio atribuye la condición de Usuario e implica aceptación plena, expresa e incondicional de estos Términos en su versión vigente. Quien no esté de acuerdo debe abstenerse de utilizarlo.</p><p>Starkio puede modificarlos en cualquier momento. La nueva versión se publicará en el Sitio y su uso continuado implicará aceptación de los cambios.</p></Section>

          <Section id="s2" title="2. Descripción del Sitio y los servicios"><p className="mb-3">Starkio Labs es un holding familiar de tecnología que desarrolla y opera empresas de Data, Software e Inteligencia Artificial. El Sitio busca:</p><ul className="list-inside list-disc space-y-1.5"><li>Presentar identidad, misión, valores y portafolio de Starkio Labs.</li><li>Informar sobre servicios, soluciones y proyectos de las empresas del holding.</li><li>Facilitar el contacto con clientes, socios, inversionistas y colaboradores.</li><li>Publicar información, noticias y actualizaciones de las actividades del holding.</li></ul><p className="mt-3">Starkio puede modificar, suspender o descontinuar el Sitio o cualquiera de sus funcionalidades, temporal o definitivamente, sin previo aviso ni responsabilidad frente al Usuario.</p></Section>

          <Section id="s3" title="3. Condiciones de acceso y uso"><h3 className="mb-2 font-semibold text-starkio-cloud/90">3.1 Requisitos del Usuario</h3><ul className="mb-5 list-inside list-disc space-y-1.5"><li>Ser mayor de 14 años; los menores deberán contar con consentimiento y supervisión de sus tutores.</li><li>Tener capacidad legal para obligarse según la legislación aplicable.</li><li>Aceptar estos Términos y la <Link href="/privacidad" className="text-starkio-purple hover:underline">Política de Privacidad</Link>.</li></ul><h3 className="mb-2 font-semibold text-starkio-cloud/90">3.2 Usos permitidos</h3><ul className="mb-5 list-inside list-disc space-y-1.5"><li>Consultar información, contenidos y servicios disponibles.</li><li>Contactar a Starkio por los canales habilitados.</li><li>Acceder a documentos, recursos o materiales públicos.</li></ul><h3 className="mb-2 font-semibold text-starkio-cloud/90">3.3 Usos prohibidos</h3><ul className="list-inside list-disc space-y-1.5"><li>Usar el Sitio con fines ilícitos, fraudulentos o contrarios a la buena fe, orden público o legislación vigente.</li><li>Reproducir, distribuir, modificar o explotar contenidos sin autorización escrita.</li><li>Introducir virus, malware, código malicioso o programas dañinos.</li><li>Intentar acceder sin autorización a sistemas, redes o servidores.</li><li>Dañar, sobrecargar, inutilizar o deteriorar el Sitio o sus redes.</li><li>Usar scraping, crawling, robots, spiders u otras herramientas automatizadas sin autorización.</li><li>Suplantar identidades, recolectar datos personales sin consentimiento o enviar spam.</li></ul></Section>

          <Section id="s4" title="4. Propiedad intelectual e industrial"><h3 className="mb-2 font-semibold text-starkio-cloud/90">4.1 Titularidad de los derechos</h3><p className="mb-2">Starkio Labs SpA es titular o licenciataria de los derechos de propiedad intelectual e industrial sobre el Sitio y sus contenidos, incluyendo las marcas Starkio y Starkio Labs, logotipos, diseño gráfico, arquitectura de información, interfaz, código fuente, textos, imágenes, iconos, software, scripts, bases de datos y sistemas subyacentes.</p><h3 className="mb-2 font-semibold text-starkio-cloud/90">4.2 Licencia limitada al Usuario</h3><p className="mb-5">Se otorga una licencia no exclusiva, intransferible, revocable y limitada para acceder y visualizar contenidos únicamente para uso personal y no comercial. No supone cesión de derechos.</p><h3 className="mb-2 font-semibold text-starkio-cloud/90">4.3 Contenidos aportados por el Usuario</h3><p>Quien envíe contenidos garantiza su autoría o contar con los derechos necesarios, y otorga a Starkio una licencia no exclusiva, gratuita, sublicenciable y transferible para usarlos en la operación del Sitio. El Usuario es responsable de la licitud, exactitud e idoneidad de sus aportes.</p></Section>

          <Section id="s5" title="5. Responsabilidad y garantías"><h3 className="mb-2 font-semibold text-starkio-cloud/90">5.1 Disponibilidad del Sitio</h3><p className="mb-5">Starkio hará esfuerzos razonables para mantener el Sitio operativo, pero no garantiza disponibilidad ininterrumpida ni ausencia de errores. Podrá suspender el acceso por mantenimiento, seguridad, actualización u otras causas justificadas sin compensación.</p><h3 className="mb-2 font-semibold text-starkio-cloud/90">5.2 Exactitud de la información</h3><p className="mb-5">Los contenidos son informativos y pueden no estar actualizados. Starkio no garantiza su exactitud, integridad, vigencia o idoneidad para una finalidad específica; el Usuario debe verificarlos antes de tomar decisiones.</p><h3 className="mb-2 font-semibold text-starkio-cloud/90">5.3 Limitación de responsabilidad</h3><p className="mb-2">En la máxima medida permitida por la ley, Starkio no será responsable por daños directos, indirectos, incidentales, especiales, consecuenciales o punitivos; errores u omisiones; interrupciones ajenas a su control; virus o malware; conducta de terceros; o pérdida de datos, negocios, ingresos o beneficios.</p><h3 className="mb-2 font-semibold text-starkio-cloud/90">5.4 Fuerza mayor</h3><p>No habrá responsabilidad por incumplimientos causados por fuerza mayor o caso fortuito, incluidos desastres naturales, fallos de infraestructura de terceros, ciberataques, pandemias, actos de autoridad u otras circunstancias fuera del control razonable de la Empresa.</p></Section>

          <Section id="s6" title="6. Enlaces a sitios de terceros"><p className="mb-3">Los enlaces a sitios de terceros se entregan solo por comodidad del Usuario y no implican aprobación, aval, recomendación ni vinculación de Starkio con dichos sitios, contenidos, productos o servicios.</p><p>Starkio no controla esos sitios y no asume responsabilidad por su contenido, disponibilidad, privacidad, seguridad ni daños derivados de su uso. El acceso es de exclusiva responsabilidad del Usuario. Un enlace de terceros al Sitio tampoco supone relación, asociación o respaldo de Starkio.</p></Section>

          <Section id="s7" title="7. Empresas del holding — Condiciones específicas"><p className="mb-4">Cada empresa del portafolio opera bajo su propia razón social, identidad y condiciones de servicio. A la vigencia de estos Términos:</p><div className="mb-4 overflow-x-auto rounded-xl border border-white/10"><table className="w-full text-left text-xs"><thead><tr className="border-b border-white/10 text-starkio-cloud/40"><th className="px-4 py-3 font-medium">Empresa</th><th className="px-4 py-3 font-medium">Área</th><th className="px-4 py-3 font-medium">Descripción</th></tr></thead><tbody><tr className="border-b border-white/5"><td className="px-4 py-3">Starck Brand Hub</td><td className="px-4 py-3">Software</td><td className="px-4 py-3">Plataforma de branding para presentaciones corporativas (PowerPoint add-in).</td></tr><tr><td className="px-4 py-3">Aqualis</td><td className="px-4 py-3">Software · Infraestructura</td><td className="px-4 py-3">Sistema de gestión para cooperativas de Agua Potable Rural (APR).</td></tr></tbody></table></div><p>Estos Términos aplican al Sitio corporativo. Los productos y plataformas de cada filial pueden tener términos propios que se pondrán a disposición al contratar o acceder a sus servicios.</p></Section>

          <Section id="s8" title="8. Política de uso aceptable de los servicios"><p className="mb-4">Al acceder a servicios digitales de empresas del holding, el Usuario se compromete a un uso responsable.</p><h3 className="mb-2 font-semibold text-starkio-cloud/90">8.1 Servicios de Software (SaaS)</h3><ul className="mb-5 list-inside list-disc space-y-1.5"><li>No realizar ingeniería inversa, descompilar, desensamblar ni intentar obtener código fuente.</li><li>No compartir credenciales con terceros no autorizados.</li><li>No procesar datos personales de terceros sin autorizaciones legales.</li><li>No usar servicios en contravención de normas de datos, propiedad intelectual o competencia desleal.</li></ul><h3 className="mb-2 font-semibold text-starkio-cloud/90">8.2 Servicios de Datos e Inteligencia Artificial</h3><ul className="list-inside list-disc space-y-1.5"><li>No usarlos para fines discriminatorios, lesivos de derechos fundamentales o contrarios a la ética.</li><li>No introducir datos falsos, fraudulentos o maliciosos.</li><li>Reconocer que los modelos de IA generan resultados probabilísticos y validar sus resultados antes de decisiones de impacto relevante.</li></ul></Section>

          <Section id="s9" title="9. Confidencialidad"><p className="mb-3">La información confidencial que el Usuario proporcione, como propuestas, proyectos o datos comerciales, será tratada de forma reservada. Esta obligación no aplica si la información es pública por causa ajena a Starkio, debe revelarse por mandato legal o fue recibida legítimamente de un tercero.</p><p>Cuando un proyecto requiera un acuerdo formal, Starkio podrá suscribir un Acuerdo de No Divulgación (NDA) específico con la contraparte.</p></Section>

          <Section id="s10" title="10. Protección de datos personales"><p className="mb-3">El tratamiento de datos personales se rige por la <Link href="/privacidad" className="text-starkio-purple hover:underline">Política de Privacidad y Uso de Cookies</Link>, que forma parte integrante de estos Términos.</p><p>Al aceptarlos, el Usuario declara haber leído y comprendido dicha política y consiente el tratamiento de sus datos. Starkio cumple con las Leyes N° 19.628 y N° 21.719, garantizando derechos de acceso, rectificación, cancelación, oposición y portabilidad.</p></Section>

          <Section id="s11" title="11. Comunicaciones electrónicas"><p className="mb-3">Al proporcionar su correo electrónico por el formulario u otros canales, el Usuario consiente recibir comunicaciones de Starkio en respuesta a su consulta o solicitud.</p><p className="mb-3">Starkio no enviará comunicaciones comerciales o de marketing sin consentimiento previo y explícito. Dicho consentimiento puede revocarse mediante el enlace de baja de cada comunicación o escribiendo a contacto@starkio.io.</p><p>Las comunicaciones de respuesta tendrán validez equivalente a las escritas en papel cuando la legislación aplicable lo permita.</p></Section>

          <Section id="s12" title="12. Nulidad parcial"><p>Si una cláusula fuera declarada nula, inválida o inaplicable por una autoridad competente, ello no afectará la vigencia del resto de los Términos. La cláusula afectada se interpretará o sustituirá, en lo posible, por una disposición válida que se aproxime a su propósito y efecto económico.</p></Section>
          <Section id="s13" title="13. Renuncia"><p>Que Starkio no ejerza o exija un derecho o disposición no constituye una renuncia. Toda renuncia deberá constar por escrito y estar firmada por el representante legal de Starkio.</p></Section>
          <Section id="s14" title="14. Cesión"><p>El Usuario no podrá ceder, transferir ni delegar derechos u obligaciones derivados de estos Términos sin consentimiento escrito de Starkio. Starkio podrá cederlos en una fusión, adquisición, reestructuración, venta de activos u operación similar, siempre que el cesionario asuma sus obligaciones frente al Usuario.</p></Section>

          <Section id="s15" title="15. Legislación aplicable y jurisdicción"><p className="mb-2">Estos Términos se rigen por la legislación de Chile, incluyendo las Leyes N° 19.496, N° 19.628, N° 21.719, N° 17.336 y N° 19.223, el Código Civil y el Código de Comercio.</p><p>Las controversias se someterán a los Tribunales Ordinarios de Justicia de Santiago de Chile. Cuando el Usuario sea consumidor, podrá también acudir al SERNAC o ejercer acciones reconocidas por la Ley N° 19.496 ante los tribunales competentes.</p></Section>
          <Section id="s16" title="16. Resolución de controversias y mediación"><p className="mb-3">Antes de iniciar una acción judicial, las partes intentarán resolver de buena fe cualquier controversia mediante negociación directa durante al menos <strong>30 días hábiles</strong> desde la notificación del conflicto.</p><p className="mb-3">Si no hay acuerdo, podrán someterla a mediación ante un mediador neutral acordado de común acuerdo, compartiendo sus costos por igual salvo acuerdo distinto.</p><p>Esto no impide solicitar medidas cautelares urgentes a los tribunales competentes cuando sea necesario proteger derechos.</p></Section>
          <Section id="s17" title="17. Vigencia y modificaciones"><p>Estos Términos entran en vigor en la fecha indicada y se mantienen vigentes mientras el Sitio esté operativo, salvo derogación o sustitución. Starkio puede actualizarlos en cualquier momento; los cambios regirán desde su publicación, salvo fecha distinta. Se recomienda revisarlos periódicamente.</p></Section>

          <Section id="s18" title="18. Contacto"><p className="mb-4">Para cualquier consulta, duda o reclamación sobre estos Términos, el Usuario puede contactar a Starkio por los siguientes canales:</p><DetailTable data={[["Empresa", "Starkio Labs SpA"], ["Email general", "contacto@starkio.io"], ["Email legal", "legal@starkio.io"], ["Sitio web", "https://starkio.io"], ["Dirección", "Santiago, Región Metropolitana, Chile"], ["Horario de atención", "Lunes a viernes, 9:00 a 18:00 hrs. (hora de Chile)"]]} /><p className="mt-4">Starkio responderá las consultas recibidas en un plazo máximo de <strong>10 días hábiles</strong>.</p></Section>

          <p className="border-t border-white/5 pt-6 text-xs text-starkio-cloud/30">Starkio Labs SpA — Santiago de Chile, 16 de septiembre de 2026. Versión 1.0 · starkio.io/terminos</p>
        </div>
      </div>
    </main>
  );
}
